---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      # - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --strict
          - --config-file=./.yamllint

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/python-poetry/poetry
    rev: 2.0.1
    hooks:
      - id: poetry-lock
      - id: poetry-check

#   - repo: https://github.com/python-poetry/poetry-plugin-export
#     rev: 1.9.0
#     hooks:
#       - id: poetry-export

  - repo: local
    hooks:
      - id: generate-json-schemas
        name: Check JSON Schemas
        language: system
        types: [python]
        entry: python generate_json_schemas.py

      - id: delete-pypi-test-releases
        name: Delete PyPI test releases
        language: system
        types: [python]
        entry: poetry run pypi-cleanup --host https://test.pypi.org --username germainlefebvre4 --package libtado
