---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      # - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.30.0
    hooks:
      - id: yamllint
        args:
          - --strict
          - --config-file=./.yamllint
