language: python
python:
  - "3.7"
install:
  - pip install requests click
git:
  quiet: true
script: python check.py $tado_username $tado_password $tado_client_secret
deploy:
  provider: pypi
  user: $pypi_username
  password: $pypi_password
  on:
    branch: master
#    tags: true
