[project]
name = "libtado"
version = "3.7.13"
description = "A library (and a command line client) to control your Tado Smart Thermostat."
authors = [
    { name = "Germain Lefebvre", email = "germain.lefebvre4@gmail.com" },
]
license = "GPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click",
    "requests",
    "python-dateutil",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
]

[project.urls]
Repository = "https://github.com/germainlefebvre4/libtado"
Homepage = "https://libtado.readthedocs.io/"
Documentation = "https://libtado.readthedocs.io/"

[project.scripts]
tado = "libtado.__main__:main"

[dependency-groups]
test = [
    "pytest",
    "pytest-dotenv",
    "python-dateutil",
]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-click",
]
lint = [
    "ruff",
]
generate = [
    "genson",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
