---
name: JSON Schemas
on:
  - workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        poetry-version: ["main"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry version ${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: |
          poetry install

      - name: Generate JSON Schemas
        run: |
          export TADO_PASSWORD=$(echo $TADO_PASSWORD_B64 | base64 -d)
          python generate_json_schemas.py
        env:
          TADO_USERNAME: ${{ secrets.TADO_USERNAME }}
          TADO_PASSWORD_B64: ${{ secrets.TADO_PASSWORD_B64 }}
          TADO_CLIENT_SECRET: ${{ secrets.TADO_CLIENT_SECRET }}
          TADO_BRIDGE_AUTHKEY: ${{ secrets.TADO_BRIDGE_AUTHKEY }}

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
        with:
          files: 'schemas/*.json'

      - name: List all changed tracked and untracked files
        env:
          CHANGED_FILES: ${{ steps.verify-changed-files.outputs.changed_files }}
        run: |
          echo "Changed files: $CHANGED_FILES"

      - name: Fail if files have changed
        uses: tj-actions/verify-changed-files@v20
        with:
          fail-if-changed: true
