---
name: Lint
on:
  - pull_request

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: chartboost/ruff-action@v1
      - name: Ruff docstring coverage (non-blocking)
        continue-on-error: true
        uses: chartboost/ruff-action@v1
        with:
          args: check --select D100,D101,D102,D103,D104,D105,D106,D107

  lint-mkdocs:
    name: Lint mkdocs files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          glob: 'docs/*.md'
