---
name: Release Management

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Semantic Release Config
        run: |
          echo '{
                   "tagFormat":"${version}",
                   "plugins": [
                      "@semantic-release/commit-analyzer",
                      "@semantic-release/release-notes-generator",
                      "@semantic-release/changelog",
                      "@semantic-release/github"
                   ]
                }
          '> .releaserc
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          branches: 'master'
          semantic_version: 19.0.2
          extra_plugins: |
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/changelog@6.0.1
            @semantic-release/github@8.0.2
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: set release_version
        id: set_release_version
        uses: noobly314/share-data@v1
        with:
          share-id: release_version
          mode: set
          key: version
          value: ${{ steps.semantic.outputs.new_release_version }}
      - name: set release_published
        id: set_release_published
        uses: noobly314/share-data@v1
        with:
          share-id: release_published
          mode: set
          key: version
          value: ${{ steps.semantic.outputs.new_release_published }}

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: get release_version
        id: release_version
        uses: noobly314/share-data@v1
        with:
          share-id: release_version
          mode: get
          key: version
      - name: get release_published
        id: release_published
        uses: noobly314/share-data@v1
        with:
          share-id: release_published
          mode: get
          key: version

      - name: Update package version
        run: |
          echo ${{ steps.release_version.outputs.data }}
          poetry version ${{ steps.release_version.outputs.data }}
        if: steps.release_published.outputs.data == 'true'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
        if: steps.release_published.outputs.data == 'true'
      - name: Build and publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config repositories.pypi https://test.pypi.org/legacy/
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry build
          poetry publish -r pypi
        if: steps.release_published.outputs.data == 'true'
