name: Release development branches

on:
  push:
    branches:
    - feat/*
    - fix/*
    - chore/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Semantic Release Config
        run: |
          echo '{
                   "tagFormat":"v${version}",
                   "plugins": [
                      "@semantic-release/commit-analyzer",
                      "@semantic-release/release-notes-generator",
                      "@semantic-release/changelog",
                      "@semantic-release/github"
                   ]
                }
          '> .releaserc
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          dry_run: true
          branches: |
            [
              'feat/*',
              'fix/*',
              'chore/*',
            ]
          semantic_version: 17.1.1
          extra_plugins: |
            @semantic-release/commit-analyzer@8.0.1
            @semantic-release/release-notes-generator@9.0.0
            @semantic-release/changelog@5.0.0
            @semantic-release/github@7.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Upload
        env:
          STACKMANAGER_VERSION: ${{ github.event.release.tag_name }}
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_APIKEY }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*

#      - name: Publish distribution 📦 to Test PyPI
#        uses: pypa/gh-action-pypi-publish@master
#        with:
#          user: ${{ secrets.PYPI_USERNAME }}
#          password: ${{ secrets.PYPI_PASSWORD }}
#          repository_url: https://test.pypi.orgi/legacy/
      - name: Publish distribution 📦 to PyPI
#        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
