---
on: workflow_call

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --dev

      - name: Run pytest
        run: |
          export TADO_PASSWORD=$(echo $TADO_PASSWORD_B64 | base64 -d)
          uv run pytest tests/api/api_test.py tests/api/tado_test.py
        env:
          # TADO_USERNAME: ${{ secrets.TADO_USERNAME }}
          # TADO_PASSWORD_B64: ${{ secrets.TADO_PASSWORD_B64 }}
          # TADO_CLIENT_SECRET: ${{ secrets.TADO_CLIENT_SECRET }}
          TADO_BRIDGE_AUTHKEY: ${{ secrets.TADO_BRIDGE_AUTHKEY }}
          # TADO_REFRESH_TOKEN: ${{ secrets.TADO_REFRESH_TOKEN }}
          TADO_CREDENTIALS_FILE: ${{ vars.TADO_CREDENTIALS_FILE }}
