---
on: workflow_call

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry tox
          poetry export --with=test --without-hashes --format=requirements.txt > requirements.txt

      - name: Test with pytest
        run: |
          tox -e py${{ matrix.python-version }},unittest
        env:
          TADO_USERNAME: ${{ secrets.TADO_USERNAME }}
          TADO_PASSWORD: ${{ secrets.TADO_PASSWORD }}
          TADO_CLIENT_SECRET: ${{ secrets.TADO_CLIENT_SECRET }}
