---
on: workflow_call

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: ["3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.11"]
        poetry-version: ["main"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry version ${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: |
          poetry self add poetry-plugin-export
          poetry export --with=test --without-hashes --format=requirements.txt > requirements.txt
          python -m pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest tests/api/test_api.py tests/api/test_tado.py
        env:
          TADO_USERNAME: ${{ secrets.TADO_USERNAME }}
          TADO_PASSWORD: ${{ secrets.TADO_PASSWORD }}
          TADO_CLIENT_SECRET: ${{ secrets.TADO_CLIENT_SECRET }}
          TADO_BRIDGE_AUTHKEY: ${{ secrets.TADO_BRIDGE_AUTHKEY }}
