---
on: workflow_call

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        # python-version: ["3.8", "3.9", "3.10", "3.11"]
        poetry-version: ["main"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry version ${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: |
          poetry install --with=test

      - name: Run pytest
        run: |
          export TADO_PASSWORD=$(echo $TADO_PASSWORD_B64 | base64 -d)
          poetry run pytest tests/api/test_api.py tests/api/test_tado.py
        env:
          # TADO_USERNAME: ${{ secrets.TADO_USERNAME }}
          # TADO_PASSWORD_B64: ${{ secrets.TADO_PASSWORD_B64 }}
          # TADO_CLIENT_SECRET: ${{ secrets.TADO_CLIENT_SECRET }}
          TADO_BRIDGE_AUTHKEY: ${{ secrets.TADO_BRIDGE_AUTHKEY }}
          # TADO_REFRESH_TOKEN: ${{ secrets.TADO_REFRESH_TOKEN }}
          TADO_CREDENTIALS_FILE: ${{ vars.TADO_CREDENTIALS_FILE }}
